name: Notify on Telegram
on: [push]
jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
    - name: Notify the commit on Telegram
      uses: Itz-fork/github-telegram-notify@main
      with:
        bot_token: '${{ secrets.BOT_TOKEN }}'
        chat_id: '${{ secrets.CHAT_ID }}'
